#!/bin/sh
set -eu

if [ "$#" -ne 1 ]; then
  echo "usage: $0 [v]MAJOR.MINOR.PATCH[-PRERELEASE][+BUILD]" >&2
  exit 2
fi

version=$1
semver_pattern='^v?(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-((0|[1-9][0-9]*|[0-9A-Za-z-]*[A-Za-z-][0-9A-Za-z-]*)(\.(0|[1-9][0-9]*|[0-9A-Za-z-]*[A-Za-z-][0-9A-Za-z-]*))*))?(\+([0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*))?$'
if ! printf '%s\n' "$version" | grep -Eq "$semver_pattern"; then
  echo "invalid semantic version: $version" >&2
  exit 2
fi
version=${version#v}

script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
output="$script_dir/../Sources/pinentry-rbw-macos/Version.swift"
tmp=$(mktemp "${TMPDIR:-/tmp}/pinentry-rbw-version.XXXXXX")
trap 'rm -f "$tmp"' EXIT HUP INT TERM

umask 022
printf '// Generated by scripts/set-version.sh.\nlet appVersion = "%s"\n' "$version" > "$tmp"
chmod 0644 "$tmp"
mv "$tmp" "$output"
trap - EXIT HUP INT TERM
